// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "nguyenhai.hoang1@etc.vn"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/apikey": {
            "post": {
                "description": "API generate apikey",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Template"
                ],
                "summary": "API generate apikey",
                "parameters": [
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/vo.GenerateApiKeyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/vo.GenerateApiKeyResponse"
                        }
                    }
                }
            }
        },
        "/v1/template/docx/render": {
            "post": {
                "security": [
                    {
                        "ApiKey": []
                    }
                ],
                "description": "API generate docx template",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Template"
                ],
                "summary": "API generate docx template",
                "parameters": [
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/vo.DocxRequestGenerate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "vo.DocxRequestGenerate": {
            "type": "object",
            "required": [
                "parameters",
                "template",
                "type"
            ],
            "properties": {
                "parameters": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "template": {
                    "type": "string"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "pdf",
                        "docx"
                    ]
                }
            }
        },
        "vo.GenerateApiKeyRequest": {
            "type": "object",
            "required": [
                "accessKeyID",
                "secretAccessKey"
            ],
            "properties": {
                "accessKeyID": {
                    "type": "string"
                },
                "secretAccessKey": {
                    "type": "string"
                }
            }
        },
        "vo.GenerateApiKeyResponse": {
            "type": "object",
            "properties": {
                "apiKey": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKey": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Document Template API",
	Description:      "C08 Document Template API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
